language: cpp
cache: apt

env:
  - SCCC_CONFIG=2015_CAMERA
  - SCCC_CONFIG=2015_MAGNETIC
  - SCCC_CONFIG=2015_CCD
  - SCCC_CONFIG=2015_CCD2
  - SCCC_CONFIG=VCAN_FX15DEV
  - SCCC_CONFIG=VCAN_Z4DEV

before_install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y --allow-unauthenticated
  - sudo apt-get update
  - sudo apt-get install gcc-arm-none-eabi

script: make all
